force-app/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Promotions</relationshipLabel>
    <relationshipName>Promotions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PromotionExtnController.cls
public class PromotionExtnController {
    public String accId{get;set;}
    public String secondaryAccIds{get;set;}
    public String accName{get;set;}
    public Promotion__c promo{get
    {
        if(promo==null){
            promo=new Promotion__c();
        }else{
            promo=promo;
        }
        return promo;
    }
    set;}
    public PromotionExtnController(ApexPages.StandardController controller) {
        
    }
    
    public PageReference save(){
        promo.Account__c=accId;
        insert promo;
        List<testNameSpacema__AccountPromotion__c> apList=new List<testNameSpacema__AccountPromotion__c>();
        for(String accId:secondaryAccIds.split(';')){
            System.debug('accId : '+accId);
            if(accId!=null && accId!=''){
                testNameSpacema__AccountPromotion__c ap=new testNameSpacema__AccountPromotion__c();
                ap.Account__c=accId;
                ap.Promotion__c=promo.Id;
                apList.add(ap);
            }
            
        }
        insert apList;
        return null;
    }

}